export const IDO_ADDRESS = "0x2814Ec44f209CE9DFD9B849c962d5A815C3C6655";

export const IDO_ABI = [
	{
		inputs: [
			{ internalType: "address", name: "_vrapAddress", type: "address" },
			{ internalType: "address", name: "_admin", type: "address" },
			{ internalType: "address", name: "_oracle", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "previousOwner", type: "address" },
			{ indexed: true, internalType: "address", name: "newOwner", type: "address" },
		],
		name: "OwnershipTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: "uint256", name: "newPremiumFee", type: "uint256" }],
		name: "PremiumFeeUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: "uint256", name: "projectId", type: "uint256" }],
		name: "ProjectApproved",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: "uint256", name: "projectId", type: "uint256" },
			{ indexed: true, internalType: "address", name: "contractAddress", type: "address" },
			{ indexed: false, internalType: "bytes", name: "ipfsHash", type: "bytes" },
			{ indexed: true, internalType: "address", name: "createdBy", type: "address" },
		],
		name: "ProjectCreated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: "uint256", name: "projectId", type: "uint256" }],
		name: "ProjectRemoved",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: "uint256", name: "newStandardFee", type: "uint256" }],
		name: "StandardFeeUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: "uint256", name: "projectId", type: "uint256" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
			{ indexed: false, internalType: "uint256", name: "totalCostInVrap", type: "uint256" },
			{ indexed: true, internalType: "address", name: "buyer", type: "address" },
		],
		name: "TokensBought",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: "uint256", name: "projectId", type: "uint256" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "TokensDeposited",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: "uint256", name: "projectId", type: "uint256" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
			{ indexed: true, internalType: "address", name: "recipient", type: "address" },
		],
		name: "TokensWithdrawn",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "address", name: "vrapTokenAddress", type: "address" }],
		name: "VrapTokenUpdated",
		type: "event",
	},
	{
		inputs: [{ internalType: "uint256", name: "_premiumFee", type: "uint256" }],
		name: "_setPremiumFee",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "projectId", type: "uint256" },
			{ internalType: "address", name: "newAddress", type: "address" },
		],
		name: "_setSettlementAddress",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_standardFee", type: "uint256" }],
		name: "_setStandardFee",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_vrapTokenAddress", type: "address" }],
		name: "_setVrapToken",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "projectId", type: "uint256" }],
		name: "approveProject",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "projectId", type: "uint256" },
			{ internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "buyTokens",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "settlementAddress", type: "address" },
			{ internalType: "bytes", name: "ipfsHash", type: "bytes" },
			{ internalType: "uint256", name: "startDate", type: "uint256" },
			{ internalType: "uint256", name: "endDate", type: "uint256" },
			{ internalType: "bool", name: "isPremium", type: "bool" },
			{ internalType: "address", name: "contractAddress", type: "address" },
			{ internalType: "uint256", name: "costPerToken", type: "uint256" },
			{ internalType: "address", name: "projectWallet", type: "address" },
		],
		name: "createProject",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "projectId", type: "uint256" },
			{ internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "depositTokens",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "projectId", type: "uint256" },
			{ internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "emergencyWithdraw",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "premiumFee",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		name: "projects",
		outputs: [
			{ internalType: "uint256", name: "projectId", type: "uint256" },
			{ internalType: "bytes", name: "ipfsHash", type: "bytes" },
			{ internalType: "address", name: "settlementAddress", type: "address" },
			{ internalType: "uint256", name: "startDate", type: "uint256" },
			{ internalType: "uint256", name: "endDate", type: "uint256" },
			{ internalType: "bool", name: "isPremium", type: "bool" },
			{ internalType: "bool", name: "isApproved", type: "bool" },
			{ internalType: "address", name: "contractAddress", type: "address" },
			{ internalType: "uint256", name: "costPerToken", type: "uint256" },
			{ internalType: "address", name: "projectWallet", type: "address" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "projectId", type: "uint256" }],
		name: "removeProject",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "standardFee",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "vrapToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
];
